### ISSUE TITLE
PID control of CO2  in a Grow Tent?

### ISSUE THREAD

**Issue by solarslurpi** [ShawnHymel/pendulum-rl#1]
Thank you for the two part YouTube series on PID control.  I left this message on the YouTube channel (pardon the two messages !)  I am trying to provide PID control of a CO2 cannister to a grow tent where plants will grow 30% more with CO2 (there are some other factors but that's the goal).  The challenge as I see it is both air distribution (made "worse" by fans blowing the air around to keep down insects, disease) and by the actual distribution of the gas (from the solenoid's flow rate but also the gas coming out within the grow tent and the uneven distribution from that).  How would you approach Kp, Ki, Kd (and perhaps bias) under this scenario? Thank you.

**Comment by ShawnHymel** [comment]
Replied on the video comments.
